### ISSUE TITLE
RuntimeError: Frame didn't arrived within 5000

### ISSUE THREAD

**Issue by barbara1990** [boku-ilen/landscapelab-lego#17]
Observed once when working with .bag file without the camera

LegoInputStream.py", line 69, in get_frame
    frames = self.pipeline.wait_for_frames()
RuntimeError: Frame didn't arrived within 5000

**Comment by chrisgraf** [comment]
what does this mean? is there a delay in playback? if it just happens in the playback of the bag file this is not as important is if it also would happen in livestream

**Comment by barbara1990** [comment]
I've observed it only once using bag file but not sure what was the reason. We could change the label to 'need observation' or something similar, because currently it doesn't cause any problems

**Comment by kb173** [comment]
Since this never happened or caused any problems during testing & workshops, we can close this. Probably just related to bad performance on @barbara1990's testing laptop.
