### ISSUE TITLE
manage imports and runtime environment; restructure 

### ISSUE THREAD

**Issue by chrisgraf** [boku-ilen/landscapelab-lego#18]
currently the project can not be started because of the structure and how the imports work. As a workaround (which also die IDE uses) we can set the python classpath. Better is a directory tree where all dependencies are below a single root (where also the main program is located)

**Comment by chrisgraf** [comment]
% python LegoDetection/main.py                                
Traceback (most recent call last):
  File "LegoDetection/main.py", line 5, in <module>
    from BoardDetector import BoardDetector
  File "/home/graf/landscapelab/landscapelab-lego/LegoDetection/BoardDetector.py", line 10, in <module>
    from LegoOutputStream import LegoOutputStream, LegoOutputChannel
  File "/home/graf/landscapelab/landscapelab-lego/LegoDetection/LegoOutputStream.py", line 5, in <module>
    from Tracker import Tracker
  File "/home/graf/landscapelab/landscapelab-lego/LegoDetection/Tracker.py", line 4, in <module>
    from LegoUI.UIElements.UIElement import UIElement
ModuleNotFoundError: No module named 'LegoUI'

**Comment by MoritzRoth** [comment]
I think this was resolved with fdeaf36b2e5760fe4e283e3d35e71f3600f1bb0f 68108d3d381a5d6101ab57d60178419555c8786c and 28af57d80418d1a880a066202a2a81eb55c7cffd
at least the program starts now

**Comment by chrisgraf** [comment]
nope still not resolved .. there are still import errors

**Comment by barbara1990** [comment]
import errors are resolved but restructure still wanted
