### ISSUE TITLE
create a screenshots modus for the camera

### ISSUE THREAD

**Issue by barbara1990** [boku-ilen/landscapelab-lego#34]
It should be possible to take screenshots of the board with the camera (lego detection not needed at that time). It needs to be cleared whether navigation should be possible.

**Comment by MoritzRoth** [comment]
Is this still relevant or did we settle on an external camera?
If I rememer correctly we also talked about taking a video instead of just sceenshots.

**Comment by chrisgraf** [comment]
external camera
