### ISSUE TITLE
Regularly get assets like the Player Position Marker from the server and display an icon

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab-lego#43]

**Comment by chrisgraf** [comment]
@barbara1990 : did you do something on this? what would be the status?

**Comment by barbara1990** [comment]
didn't start working on this issue, there is only a new icon in resources: symbol_player_position

**Comment by barbara1990** [comment]
mostly implemented, added as a virtual brick, need testing
TODO: remove the previous virtual brick so that only one is visible at the same time

**Comment by barbara1990** [comment]
implemented, need testing
