### ISSUE TITLE
add virtual yes/no in the evaluation program stage

### ISSUE THREAD

**Issue by barbara1990** [boku-ilen/landscapelab-lego#45]

**Comment by chrisgraf** [comment]
@barbara1990 : what's the status on this?

**Comment by barbara1990** [comment]
trying to implement a working solution 
(avoid error:
ImageHandler.py", line 74, in img_on_background
    img = im_top['image']
TypeError: 'NoneType' object is not subscriptable)

**Comment by barbara1990** [comment]
implemented, need testing, the colour of virtual yes/no bricks might be too bright
