### ISSUE TITLE
Make UI graphics brighter to prevent accidental detection

### ISSUE THREAD

**Issue by kb173** [boku-ilen/landscapelab-lego#52]
We already made them brighter before the first workshop, but we should increase the brightness (decrease the contrast to the background) further to prevent accidental detection if we have a scenario where the room is even darker or the projector is even closer.

**Comment by MoritzRoth** [comment]
increased brightness with https://github.com/boku-ilen/landscapelab-lego/commit/677461b26ea54fece96b61480b868183878985f3
